export { useFilter } from './useFilter';
export { usePatientQueue } from './usePatientQueue'; 
export { usePatientManagement } from './usePatientManagement';
export { useQueueStats } from './useQueueStats';
export { usePatientCard, getStatusColor, getStatusBgColor } from './usePatientCard';
export { useNumericInput, useFormValidation } from './useNumericInput';
export { useStaff } from './useStaff';
export { usePatientHistory } from './usePatientHistory';
export { useConsultation } from './useConsultation';
export { useAuth } from './authentication/useAuth';
export { useForm } from './authentication/useForm';
export { loginValidation, registerValidation } from './authentication/useValidation';
